### ISSUE TITLE
You must have the following installed to add the SignalFx repo keys [dirmngr] on Debian Jessie

### ISSUE THREAD

**Issue by geerlingguy** [signalfx/puppet_collectd#66]
When installing via https://dl.signalfx.com/collectd-install, I started getting the following error, starting last Friday, April 6:

```
Getting SignalFx collectd package
You must have the following installed to add the SignalFx repo keys [dirmngr]
```

It looks like dirmngr was recently added to support Debian Stretch, but it's not installed on Jessie.

**Comment by codesmith14** [comment]
Thank you for reporting this issue.  This should only have affected our collectd installer script which can be found [here](https://github.com/signalfx/signalfx-collectd-installer).  We have since updated the installer script to automatically install dirmngr if it is needed.  The change went in with this [pull request](https://github.com/signalfx/signalfx-collectd-installer/commit/dad40719295a53f8b3c5c0d3b7ff8d10e51c7071).  This dependency is only required if gpg2 is installed.  Please let us know if you experience any further issues.
